---
- hosts: test
  become: true
  gather_facts: False
  vars:
      region: us-east-1
      hostpath: "hosts"
      instance_type: t2.micro
      ami: ami-0dfcb1ef8550277af  
      keypair: assessment # pem file name
      subnetid: subnet-08faf2b2a17ee8c94 #subnet-0e80c6bbb664c7138
      mysql_root_password: "wordpress"
      db_name: "wordpress"
      db_user: "wordpress"
      db_password: "wordpress"
      wp_db_host: "localhost"
      wp_db_prefix: "wp_"
      wp_admin_user: "admin"
      wp_admin_password: "admin"
      wp_admin_email: "baldurinaveen1@gmail.com"

  tasks:
    - name: Install WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/latest.tar.gz"
     
    - name: Extract WordPress
      unarchive:
        src: "/tmp/latest.tar.gz"
        dest: "/var/www/html"
        remote_src: yes
     
    - name: Create wp-config.php
      copy:
        content: |
          <?php
          define( 'DB_NAME', '{{ db_name }}' );
          define( 'DB_USER', '{{ db_user }}' );
          define( 'DB_PASSWORD', '{{ db_password }}' );
          define( 'DB_HOST', '{{ wp_db_host }}' );
          define( 'DB_CHARSET', 'utf8mb4' );
          define( 'DB_COLLATE', '' );
          define( 'AUTH_KEY',         'put your unique phrase here' );
          define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
          define( 'LOGGED_IN_KEY

